from enum import Enum


class ErrorCode(str, Enum):
    """에러 코드 열거형 (최적화 버전)"""
    
    # --- 공통 및 시스템 에러 ---
    BAD_REQUEST = "BAD_REQUEST"           # 400: 잘못된 요청 (파싱 실패 등)
    UNAUTHORIZED = "UNAUTHORIZED"         # 401: 인증 필요
    FORBIDDEN = "FORBIDDEN"               # 403: 권한 없음
    NOT_FOUND = "NOT_FOUND"               # 404: 리소스 없음
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED" # 405
    TOO_MANY_REQUEST = "TOO_MANY_REQUEST" # 429: 빈도 초과
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR" # 500

    # --- 검증 에러 (설계도 60라인) ---
    INVALID_INPUT = "INVALID_INPUT"       # 422: 형식은 맞으나 도메인 규칙 위반

    # --- 인증 관련 핵심 도메인 에러 ---
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS" # 401: 로그인 실패
    ALREADY_LOGIN = "ALREADY_LOGIN"             # 409: 이미 로그인 상태
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS" # 409: 이메일 중복
    NICKNAME_ALREADY_EXISTS = "NICKNAME_ALREADY_EXISTS" # 409: 닉네임 중복

    # --- 리소스 존재 여부 핵심 에러 ---
    USER_NOT_FOUND = "USER_NOT_FOUND"     # 404
    POST_NOT_FOUND = "POST_NOT_FOUND"     # 404
    COMMENT_NOT_FOUND = "COMMENT_NOT_FOUND" # 404

    # --- 기타 설계도 명시 특수 에러 ---
    POST_ALREADY_LIKED = "POST_ALREADY_LIKED"     # 409
    POST_ALREADY_UNLIKED = "POST_ALREADY_UNLIKED" # 409
    PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE"       # 413
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"   # 429


class SuccessCode(str, Enum):
    """성공 코드 열거형 (최적화 버전)"""
    
    # 설계도(CSV)에 명시된 성공 코드들
    SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    AUTH_SUCCESS = "AUTH_SUCCESS"
    EMAIL_AVAILABLE = "EMAIL_AVAILABLE"
    NICKNAME_AVAILABLE = "NICKNAME_AVAILABLE"
    
    USER_FETCHED = "USER_FETCHED"
    USER_RETRIEVED = "USER_RETRIEVED"
    USER_UPDATED = "USER_UPDATED"
    USER_PASSWORD_UPDATED = "USER_PASSWORD_UPDATED"
    PROFILE_IMAGE_UPLOADED = "PROFILE_IMAGE_UPLOADED"
    
    POSTS_RETRIEVED = "POSTS_RETRIEVED"
    POST_RETRIEVED = "POST_RETRIEVED"
    POST_CREATED = "POST_CREATED"
    POST_UPDATED = "POST_UPDATED"
    POST_DELETED = "POST_DELETED"
    POST_FILE_UPLOADED = "POST_FILE_UPLOADED"
    POST_LIKE_CREATED = "POST_LIKE_CREATED"
    POST_LIKE_DELETED = "POST_LIKE_DELETED"
    POST_LIKE_UPDATED = "POST_LIKE_UPDATED"
    
    COMMENTS_RETRIEVED = "COMMENTS_RETRIEVED"
    COMMENT_CREATED = "COMMENT_CREATED"
    COMMENT_UPDATED = "COMMENT_UPDATED"
    COMMENT_DELETED = "COMMENT_DELETED"
    
    LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
    HEALTH_CHECK_OK = "HEALTH_CHECK_OK"


# 에러 상태 코드 매핑
ERROR_STATUS_MAP = {
    ErrorCode.BAD_REQUEST: 400,
    ErrorCode.UNAUTHORIZED: 401,
    ErrorCode.INVALID_CREDENTIALS: 401,
    ErrorCode.FORBIDDEN: 403,
    ErrorCode.NOT_FOUND: 404,
    ErrorCode.USER_NOT_FOUND: 404,
    ErrorCode.POST_NOT_FOUND: 404,
    ErrorCode.COMMENT_NOT_FOUND: 404,
    ErrorCode.METHOD_NOT_ALLOWED: 405,
    ErrorCode.EMAIL_ALREADY_EXISTS: 409,
    ErrorCode.NICKNAME_ALREADY_EXISTS: 409,
    ErrorCode.ALREADY_LOGIN: 409,
    ErrorCode.POST_ALREADY_LIKED: 409,
    ErrorCode.POST_ALREADY_UNLIKED: 409,
    ErrorCode.PAYLOAD_TOO_LARGE: 413,
    ErrorCode.INVALID_INPUT: 422,
    ErrorCode.TOO_MANY_REQUEST: 429,
    ErrorCode.RATE_LIMIT_EXCEEDED: 429,
    ErrorCode.INTERNAL_SERVER_ERROR: 500,
}


def get_error_status(code: ErrorCode) -> int:
    return ERROR_STATUS_MAP.get(code, 400)


def get_success_message(code: SuccessCode) -> str:
    return "요청이 성공적으로 처리되었습니다."
